//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoMidiPlayer.Data.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "18.7.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://github.com/Jed556/AutoMidiPlayer/blob/main/LICENSE.md")]
        public string LicenseUri {
            get {
                return ((string)(this["LicenseUri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://github.com/Jed556/AutoMidiPlayer/blob/main/THIRD-PARTY-NOTICES.md")]
        public string ThirdPartyLicenseUri {
            get {
                return ((string)(this["ThirdPartyLicenseUri"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int UpdateCheckFrequency {
            get {
                return ((int)(this["UpdateCheckFrequency"]));
            }
            set {
                this["UpdateCheckFrequency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoDownloadUpdates {
            get {
                return ((bool)(this["AutoDownloadUpdates"]));
            }
            set {
                this["AutoDownloadUpdates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoCheckUpdates {
            get {
                return ((bool)(this["AutoCheckUpdates"]));
            }
            set {
                this["AutoCheckUpdates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IncludeBetaUpdates {
            get {
                return ((bool)(this["IncludeBetaUpdates"]));
            }
            set {
                this["IncludeBetaUpdates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HoldNotes {
            get {
                return ((bool)(this["HoldNotes"]));
            }
            set {
                this["HoldNotes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TransposeNotes {
            get {
                return ((bool)(this["TransposeNotes"]));
            }
            set {
                this["TransposeNotes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MergeNotes {
            get {
                return ((bool)(this["MergeNotes"]));
            }
            set {
                this["MergeNotes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseSpeakers {
            get {
                return ((bool)(this["UseSpeakers"]));
            }
            set {
                this["UseSpeakers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoEnableListenMode {
            get {
                return ((bool)(this["AutoEnableListenMode"]));
            }
            set {
                this["AutoEnableListenMode"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SyncFavoritesToMidiShow {
            get {
                return ((bool)(this["SyncFavoritesToMidiShow"]));
            }
            set {
                this["SyncFavoritesToMidiShow"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoDetectDefaultKey {
            get {
                return ((bool)(this["AutoDetectDefaultKey"]));
            }
            set {
                this["AutoDetectDefaultKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultSongArtist {
            get {
                return ((string)(this["DefaultSongArtist"]));
            }
            set {
                this["DefaultSongArtist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultSongAlbum {
            get {
                return ((string)(this["DefaultSongAlbum"]));
            }
            set {
                this["DefaultSongAlbum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DefaultSongDefaultKey {
            get {
                return ((int)(this["DefaultSongDefaultKey"]));
            }
            set {
                this["DefaultSongDefaultKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DefaultSongKey {
            get {
                return ((int)(this["DefaultSongKey"]));
            }
            set {
                this["DefaultSongKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DefaultSongTranspose {
            get {
                return ((int)(this["DefaultSongTranspose"]));
            }
            set {
                this["DefaultSongTranspose"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DefaultSongCustomBpm {
            get {
                return ((double)(this["DefaultSongCustomBpm"]));
            }
            set {
                this["DefaultSongCustomBpm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double DefaultSongSpeed {
            get {
                return ((double)(this["DefaultSongSpeed"]));
            }
            set {
                this["DefaultSongSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DefaultSongMergeNotes {
            get {
                return ((bool)(this["DefaultSongMergeNotes"]));
            }
            set {
                this["DefaultSongMergeNotes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public uint DefaultSongMergeMilliseconds {
            get {
                return ((uint)(this["DefaultSongMergeMilliseconds"]));
            }
            set {
                this["DefaultSongMergeMilliseconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DefaultSongHoldNotes {
            get {
                return ((bool)(this["DefaultSongHoldNotes"]));
            }
            set {
                this["DefaultSongHoldNotes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PlayUnplayableOnIgnore {
            get {
                return ((bool)(this["PlayUnplayableOnIgnore"]));
            }
            set {
                this["PlayUnplayableOnIgnore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int AppTheme {
            get {
                return ((int)(this["AppTheme"]));
            }
            set {
                this["AppTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectedLayout {
            get {
                return ((int)(this["SelectedLayout"]));
            }
            set {
                this["SelectedLayout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int SelectedSpeed {
            get {
                return ((int)(this["SelectedSpeed"]));
            }
            set {
                this["SelectedSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint MergeMilliseconds {
            get {
                return ((uint)(this["MergeMilliseconds"]));
            }
            set {
                this["MergeMilliseconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeRequired {
            get {
                return ((bool)(this["UpgradeRequired"]));
            }
            set {
                this["UpgradeRequired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GenshinImpact.exe")]
        public string GenshinLocation {
            get {
                return ((string)(this["GenshinLocation"]));
            }
            set {
                this["GenshinLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HTGame.exe")]
        public string NTELocation {
            get {
                return ((string)(this["NTELocation"]));
            }
            set {
                this["NTELocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RobloxPlayerBeta.exe")]
        public string RobloxLocation {
            get {
                return ((string)(this["RobloxLocation"]));
            }
            set {
                this["RobloxLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sky.exe")]
        public string SkyLocation {
            get {
                return ((string)(this["SkyLocation"]));
            }
            set {
                this["SkyLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("xdt.exe")]
        public string HeartopiaLocation {
            get {
                return ((string)(this["HeartopiaLocation"]));
            }
            set {
                this["HeartopiaLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BPSR.exe")]
        public string BPSRLocation {
            get {
                return ((string)(this["BPSRLocation"]));
            }
            set {
                this["BPSRLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Harry Potter Magic Awakened.exe")]
        public string HPMALocation {
            get {
                return ((string)(this["HPMALocation"]));
            }
            set {
                this["HPMALocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ActiveGenshin {
            get {
                return ((bool)(this["ActiveGenshin"]));
            }
            set {
                this["ActiveGenshin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ActiveNTE {
            get {
                return ((bool)(this["ActiveNTE"]));
            }
            set {
                this["ActiveNTE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ActiveRoblox {
            get {
                return ((bool)(this["ActiveRoblox"]));
            }
            set {
                this["ActiveRoblox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ActiveSky {
            get {
                return ((bool)(this["ActiveSky"]));
            }
            set {
                this["ActiveSky"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ActiveHeartopia {
            get {
                return ((bool)(this["ActiveHeartopia"]));
            }
            set {
                this["ActiveHeartopia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ActiveBPSR {
            get {
                return ((bool)(this["ActiveBPSR"]));
            }
            set {
                this["ActiveBPSR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ActiveHPMA {
            get {
                return ((bool)(this["ActiveHPMA"]));
            }
            set {
                this["ActiveHPMA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectedInstrument {
            get {
                return ((int)(this["SelectedInstrument"]));
            }
            set {
                this["SelectedInstrument"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MidiFolder {
            get {
                return ((string)(this["MidiFolder"]));
            }
            set {
                this["MidiFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoScanMidiFolder {
            get {
                return ((bool)(this["AutoScanMidiFolder"]));
            }
            set {
                this["AutoScanMidiFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ExcludedAutoImportPaths {
            get {
                return ((string)(this["ExcludedAutoImportPaths"]));
            }
            set {
                this["ExcludedAutoImportPaths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SongsSortMode {
            get {
                return ((int)(this["SongsSortMode"]));
            }
            set {
                this["SongsSortMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SongsSortAscending {
            get {
                return ((bool)(this["SongsSortAscending"]));
            }
            set {
                this["SongsSortAscending"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string QueueSongIds {
            get {
                return ((string)(this["QueueSongIds"]));
            }
            set {
                this["QueueSongIds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool QueueShuffle {
            get {
                return ((bool)(this["QueueShuffle"]));
            }
            set {
                this["QueueShuffle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int QueueLoopMode {
            get {
                return ((int)(this["QueueLoopMode"]));
            }
            set {
                this["QueueLoopMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CurrentSongId {
            get {
                return ((string)(this["CurrentSongId"]));
            }
            set {
                this["CurrentSongId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double CurrentSongPosition {
            get {
                return ((double)(this["CurrentSongPosition"]));
            }
            set {
                this["CurrentSongPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#1DB954")]
        public string AccentColor {
            get {
                return ((string)(this["AccentColor"]));
            }
            set {
                this["AccentColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseDirectInput {
            get {
                return ((bool)(this["UseDirectInput"]));
            }
            set {
                this["UseDirectInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseWindowMessage {
            get {
                return ((bool)(this["UseWindowMessage"]));
            }
            set {
                this["UseWindowMessage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int KeyboardPressDelayMs {
            get {
                return ((int)(this["KeyboardPressDelayMs"]));
            }
            set {
                this["KeyboardPressDelayMs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableKeyUp {
            get {
                return ((bool)(this["EnableKeyUp"]));
            }
            set {
                this["EnableKeyUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Songs")]
        public string LastViewedPage {
            get {
                return ((string)(this["LastViewedPage"]));
            }
            set {
                this["LastViewedPage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HotkeysEnabled {
            get {
                return ((bool)(this["HotkeysEnabled"]));
            }
            set {
                this["HotkeysEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MouseStopClickMode {
            get {
                return ((int)(this["MouseStopClickMode"]));
            }
            set {
                this["MouseStopClickMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3|18")]
        public string HotkeyPlayPause {
            get {
                return ((string)(this["HotkeyPlayPause"]));
            }
            set {
                this["HotkeyPlayPause"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3|25")]
        public string HotkeyNext {
            get {
                return ((string)(this["HotkeyNext"]));
            }
            set {
                this["HotkeyNext"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3|23")]
        public string HotkeyPrevious {
            get {
                return ((string)(this["HotkeyPrevious"]));
            }
            set {
                this["HotkeyPrevious"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3|24")]
        public string HotkeySpeedUp {
            get {
                return ((string)(this["HotkeySpeedUp"]));
            }
            set {
                this["HotkeySpeedUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3|26")]
        public string HotkeySpeedDown {
            get {
                return ((string)(this["HotkeySpeedDown"]));
            }
            set {
                this["HotkeySpeedDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3|13")]
        public string HotkeyPanic {
            get {
                return ((string)(this["HotkeyPanic"]));
            }
            set {
                this["HotkeyPanic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("QWERTY")]
        public string SelectedLayoutName {
            get {
                return ((string)(this["SelectedLayoutName"]));
            }
            set {
                this["SelectedLayoutName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SelectedInstrumentByGame {
            get {
                return ((string)(this["SelectedInstrumentByGame"]));
            }
            set {
                this["SelectedInstrumentByGame"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SmoothScrollingEnabled {
            get {
                return ((bool)(this["SmoothScrollingEnabled"]));
            }
            set {
                this["SmoothScrollingEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DebugModeEnabled {
            get {
                return ((bool)(this["DebugModeEnabled"]));
            }
            set {
                this["DebugModeEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int CrashLogVerbosity {
            get {
                return ((int)(this["CrashLogVerbosity"]));
            }
            set {
                this["CrashLogVerbosity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LogPlayedNotes {
            get {
                return ((bool)(this["LogPlayedNotes"]));
            }
            set {
                this["LogPlayedNotes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SelectedTransition {
            get {
                return ((int)(this["SelectedTransition"]));
            }
            set {
                this["SelectedTransition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22")]
        public int AutoCorrectThreshold {
            get {
                return ((int)(this["AutoCorrectThreshold"]));
            }
            set {
                this["AutoCorrectThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PageCaching {
            get {
                return ((bool)(this["PageCaching"]));
            }
            set {
                this["PageCaching"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TelemetryOptIn {
            get {
                return ((bool)(this["TelemetryOptIn"]));
            }
            set {
                this["TelemetryOptIn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HasShownFirstLaunch {
            get {
                return ((bool)(this["HasShownFirstLaunch"]));
            }
            set {
                this["HasShownFirstLaunch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SustainEnabledByGame {
            get {
                return ((string)(this["SustainEnabledByGame"]));
            }
            set {
                this["SustainEnabledByGame"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SustainKeyByLayout {
            get {
                return ((string)(this["SustainKeyByLayout"]));
            }
            set {
                this["SustainKeyByLayout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SostenutoKeyByLayout {
            get {
                return ((string)(this["SostenutoKeyByLayout"]));
            }
            set {
                this["SostenutoKeyByLayout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UnaCordaKeyByLayout {
            get {
                return ((string)(this["UnaCordaKeyByLayout"]));
            }
            set {
                this["UnaCordaKeyByLayout"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ReportedOptEventStatus {
            get {
                return ((int)(this["ReportedOptEventStatus"]));
            }
            set {
                this["ReportedOptEventStatus"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("history.db")]
        public string SqliteConnection {
            get {
                return ((string)(this["SqliteConnection"]));
            }
        }
    }
}
